export { default as HomeNavbar } from "./HomeNavbar/HomeNavbar"
export { default as Hero } from "./Hero"
export { default as Features } from "./Features"
export { default as Footer } from "./Footer"
export { default as Pricing } from "./Pricing"
export { default as Education } from "./Education"
export { default as Brand } from "./Brand"
export { default as MarketPlace } from "./MarketPlace"