
export const APIS = [
    {
        id: "0001",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "verified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0002",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "unverified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0003",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "verified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0004",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "unverified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0005",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "verified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0006",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "unverified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0007",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "verified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0008",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "unverified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0009",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "verified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
];

export const CATEGORIES = [
    "data",
    "sports",
    "finance",
    "travel",
    "entertainment",
    "location",
    "science",
    "food",
    "transportation",
    "music",
    "business",
    "visual recognition",
    "tools",
    "text analysis",
    "weather",

];

export const USER = [{
    id : '0001',
    fullName : 'Dummy Name',
    email : 'Dummyname@gmail.com',
    userName : 'Dummzy',
    userId : '11223344556677',
    profileId : '11aa22bb33cc44dd55ee',
    image : '/images/pro-pics.png',
}]


export const LOGINHISTORIES = [
    "2022-06-12 13:24pm",
    "2022-07-11 12:25pm",
    "2012-04-02 13:44pm",
    "2015-06-04 15:24pm",
    "2018-12-23 17:24pm",
    "2020-06-04 03:24pm",
    "2012-06-12 06:24pm",
    "2014-06-22 13:24pm",
    "2013-06-12 09:24pm",
    "2012-06-25 10:24pm",
    "2010-06-17 15:24pm",
];