
export const APIS = [
    {
        id: "0001",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "verified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0002",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "unverified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0003",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "verified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0004",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "unverified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0005",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "verified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0006",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "unverified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0007",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "verified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0008",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "unverified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
    {
        id: "0009",
        name: "Text Summarizer API",
        description: "The simplest and most effective way to skip the plenty text, and focus on the main points in ... ",
        status: "verified",
        image: "/images/zapi-logo.png",
        latency: 300,
        popularity: 9.9,
        service_level: 100,
    },
];

export const CATEGORIES = [
    "data",
    "sports",
    "finance",
    "travel",
    "entertainment",
    "location",
    "science",
    "food",
    "transportation",
    "music",
    "business",
    "visual recognition",
    "tools",
    "text analysis",
    "weather",
];